version: '3'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules #use node_modules in container. dont reference local directory
      - .:/app #map files in current directory to app folder in container
  tests:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules #use node_modules in container. dont reference local directory
      - .:/app #map files in current directory to app folder in container
    command: ["npm", "run", "test"] #override startup command in container